// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_eac_entLookup_middleware from "./routes/api/eac/[entLookup]/_middleware.ts";
import * as $api_eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_data_lake_fileSystem_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/data-lake/[fileSystem]/index.ts";
import * as $api_eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_explorer_db_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/explorer/[db]/index.ts";
import * as $api_eac_entLookup_azure_cloudLookup_api_versions_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/api-versions/index.ts";
import * as $api_eac_entLookup_azure_cloudLookup_auth_token_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/auth-token/index.ts";
import * as $api_eac_entLookup_azure_cloudLookup_locations_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/locations/index.ts";
import * as $api_eac_entLookup_azure_cloudLookup_providers_index from "./routes/api/eac/[entLookup]/azure/[cloudLookup]/providers/index.ts";
import * as $api_eac_entLookup_connections_index from "./routes/api/eac/[entLookup]/connections/index.ts";
import * as $api_eac_entLookup_index from "./routes/api/eac/[entLookup]/index.ts";
import * as $api_eac_entLookup_status_commitId_index from "./routes/api/eac/[entLookup]/status/[commitId]/index.ts";
import * as $api_eac_entLookup_status_current from "./routes/api/eac/[entLookup]/status/current.ts";
import * as $api_eac_entLookup_status_index from "./routes/api/eac/[entLookup]/status/index.ts";
import * as $api_eac_entLookup_users from "./routes/api/eac/[entLookup]/users.ts";
import * as $api_eac_middleware from "./routes/api/eac/_middleware.ts";
import * as $api_eac_handlers_clouds_check from "./routes/api/eac/handlers/clouds/check.ts";
import * as $api_eac_handlers_clouds_connections from "./routes/api/eac/handlers/clouds/connections.ts";
import * as $api_eac_handlers_clouds_helpers from "./routes/api/eac/handlers/clouds/helpers.ts";
import * as $api_eac_handlers_clouds_index from "./routes/api/eac/handlers/clouds/index.ts";
import * as $api_eac_handlers_devops_actions_check from "./routes/api/eac/handlers/devops-actions/check.ts";
import * as $api_eac_handlers_devops_actions_connections from "./routes/api/eac/handlers/devops-actions/connections.ts";
import * as $api_eac_handlers_devops_actions_helpers from "./routes/api/eac/handlers/devops-actions/helpers.ts";
import * as $api_eac_handlers_devops_actions_index from "./routes/api/eac/handlers/devops-actions/index.ts";
import * as $api_eac_handlers_github_apps_check from "./routes/api/eac/handlers/github-apps/check.ts";
import * as $api_eac_handlers_github_apps_connections from "./routes/api/eac/handlers/github-apps/connections.ts";
import * as $api_eac_handlers_github_apps_helpers from "./routes/api/eac/handlers/github-apps/helpers.ts";
import * as $api_eac_handlers_github_apps_index from "./routes/api/eac/handlers/github-apps/index.ts";
import * as $api_eac_handlers_iot_check from "./routes/api/eac/handlers/iot/check.ts";
import * as $api_eac_handlers_iot_connections from "./routes/api/eac/handlers/iot/connections.ts";
import * as $api_eac_handlers_iot_helpers from "./routes/api/eac/handlers/iot/helpers.ts";
import * as $api_eac_handlers_iot_index from "./routes/api/eac/handlers/iot/index.ts";
import * as $api_eac_handlers_secrets_check from "./routes/api/eac/handlers/secrets/check.ts";
import * as $api_eac_handlers_secrets_connections from "./routes/api/eac/handlers/secrets/connections.ts";
import * as $api_eac_handlers_secrets_helpers from "./routes/api/eac/handlers/secrets/helpers.ts";
import * as $api_eac_handlers_secrets_index from "./routes/api/eac/handlers/secrets/index.ts";
import * as $api_eac_handlers_source_connections_check from "./routes/api/eac/handlers/source-connections/check.ts";
import * as $api_eac_handlers_source_connections_connections from "./routes/api/eac/handlers/source-connections/connections.ts";
import * as $api_eac_handlers_source_connections_helpers from "./routes/api/eac/handlers/source-connections/helpers.ts";
import * as $api_eac_handlers_source_connections_index from "./routes/api/eac/handlers/source-connections/index.ts";
import * as $api_eac_handlers_sources_check from "./routes/api/eac/handlers/sources/check.ts";
import * as $api_eac_handlers_sources_connections from "./routes/api/eac/handlers/sources/connections.ts";
import * as $api_eac_handlers_sources_helpers from "./routes/api/eac/handlers/sources/helpers.ts";
import * as $api_eac_handlers_sources_index from "./routes/api/eac/handlers/sources/index.ts";
import * as $api_eac_index from "./routes/api/eac/index.ts";
import * as $api_eac_jwt from "./routes/api/eac/jwt.ts";
import * as $api_eac_list from "./routes/api/eac/list.ts";
import * as $api_github_webhooks from "./routes/api/github/webhooks.ts";
import * as $dashboard_middleware from "./routes/dashboard/_middleware.tsx";
import * as $dashboard_api_eac_index from "./routes/dashboard/api/eac/index.ts";
import * as $dashboard_azure_access_signin_callback from "./routes/dashboard/azure/access/signin/callback.ts";
import * as $dashboard_azure_access_signin_index from "./routes/dashboard/azure/access/signin/index.ts";
import * as $dashboard_azure_access_signout from "./routes/dashboard/azure/access/signout.ts";
import * as $dashboard_clouds_azure_index from "./routes/dashboard/clouds/azure/index.tsx";
import * as $dashboard_clouds_azure_new from "./routes/dashboard/clouds/azure/new.tsx";
import * as $dashboard_clouds_calz from "./routes/dashboard/clouds/calz.tsx";
import * as $dashboard_enterprise_index from "./routes/dashboard/enterprise/index.tsx";
import * as $dashboard_github_app_index from "./routes/dashboard/github-app/index.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_jwt_index from "./routes/dashboard/jwt/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $EntepriseManagementItem from "./islands/EntepriseManagementItem.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/eac/[entLookup]/_middleware.ts":
      $api_eac_entLookup_middleware,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/data-lake/[fileSystem]/index.ts":
      $api_eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_data_lake_fileSystem_index,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/explorer/[db]/index.ts":
      $api_eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_explorer_db_index,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/api-versions/index.ts":
      $api_eac_entLookup_azure_cloudLookup_api_versions_index,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/auth-token/index.ts":
      $api_eac_entLookup_azure_cloudLookup_auth_token_index,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/locations/index.ts":
      $api_eac_entLookup_azure_cloudLookup_locations_index,
    "./routes/api/eac/[entLookup]/azure/[cloudLookup]/providers/index.ts":
      $api_eac_entLookup_azure_cloudLookup_providers_index,
    "./routes/api/eac/[entLookup]/connections/index.ts":
      $api_eac_entLookup_connections_index,
    "./routes/api/eac/[entLookup]/index.ts": $api_eac_entLookup_index,
    "./routes/api/eac/[entLookup]/status/[commitId]/index.ts":
      $api_eac_entLookup_status_commitId_index,
    "./routes/api/eac/[entLookup]/status/current.ts":
      $api_eac_entLookup_status_current,
    "./routes/api/eac/[entLookup]/status/index.ts":
      $api_eac_entLookup_status_index,
    "./routes/api/eac/[entLookup]/users.ts": $api_eac_entLookup_users,
    "./routes/api/eac/_middleware.ts": $api_eac_middleware,
    "./routes/api/eac/handlers/clouds/check.ts": $api_eac_handlers_clouds_check,
    "./routes/api/eac/handlers/clouds/connections.ts":
      $api_eac_handlers_clouds_connections,
    "./routes/api/eac/handlers/clouds/helpers.ts":
      $api_eac_handlers_clouds_helpers,
    "./routes/api/eac/handlers/clouds/index.ts": $api_eac_handlers_clouds_index,
    "./routes/api/eac/handlers/devops-actions/check.ts":
      $api_eac_handlers_devops_actions_check,
    "./routes/api/eac/handlers/devops-actions/connections.ts":
      $api_eac_handlers_devops_actions_connections,
    "./routes/api/eac/handlers/devops-actions/helpers.ts":
      $api_eac_handlers_devops_actions_helpers,
    "./routes/api/eac/handlers/devops-actions/index.ts":
      $api_eac_handlers_devops_actions_index,
    "./routes/api/eac/handlers/github-apps/check.ts":
      $api_eac_handlers_github_apps_check,
    "./routes/api/eac/handlers/github-apps/connections.ts":
      $api_eac_handlers_github_apps_connections,
    "./routes/api/eac/handlers/github-apps/helpers.ts":
      $api_eac_handlers_github_apps_helpers,
    "./routes/api/eac/handlers/github-apps/index.ts":
      $api_eac_handlers_github_apps_index,
    "./routes/api/eac/handlers/iot/check.ts": $api_eac_handlers_iot_check,
    "./routes/api/eac/handlers/iot/connections.ts":
      $api_eac_handlers_iot_connections,
    "./routes/api/eac/handlers/iot/helpers.ts": $api_eac_handlers_iot_helpers,
    "./routes/api/eac/handlers/iot/index.ts": $api_eac_handlers_iot_index,
    "./routes/api/eac/handlers/secrets/check.ts":
      $api_eac_handlers_secrets_check,
    "./routes/api/eac/handlers/secrets/connections.ts":
      $api_eac_handlers_secrets_connections,
    "./routes/api/eac/handlers/secrets/helpers.ts":
      $api_eac_handlers_secrets_helpers,
    "./routes/api/eac/handlers/secrets/index.ts":
      $api_eac_handlers_secrets_index,
    "./routes/api/eac/handlers/source-connections/check.ts":
      $api_eac_handlers_source_connections_check,
    "./routes/api/eac/handlers/source-connections/connections.ts":
      $api_eac_handlers_source_connections_connections,
    "./routes/api/eac/handlers/source-connections/helpers.ts":
      $api_eac_handlers_source_connections_helpers,
    "./routes/api/eac/handlers/source-connections/index.ts":
      $api_eac_handlers_source_connections_index,
    "./routes/api/eac/handlers/sources/check.ts":
      $api_eac_handlers_sources_check,
    "./routes/api/eac/handlers/sources/connections.ts":
      $api_eac_handlers_sources_connections,
    "./routes/api/eac/handlers/sources/helpers.ts":
      $api_eac_handlers_sources_helpers,
    "./routes/api/eac/handlers/sources/index.ts":
      $api_eac_handlers_sources_index,
    "./routes/api/eac/index.ts": $api_eac_index,
    "./routes/api/eac/jwt.ts": $api_eac_jwt,
    "./routes/api/eac/list.ts": $api_eac_list,
    "./routes/api/github/webhooks.ts": $api_github_webhooks,
    "./routes/dashboard/_middleware.tsx": $dashboard_middleware,
    "./routes/dashboard/api/eac/index.ts": $dashboard_api_eac_index,
    "./routes/dashboard/azure/access/signin/callback.ts":
      $dashboard_azure_access_signin_callback,
    "./routes/dashboard/azure/access/signin/index.ts":
      $dashboard_azure_access_signin_index,
    "./routes/dashboard/azure/access/signout.ts":
      $dashboard_azure_access_signout,
    "./routes/dashboard/clouds/azure/index.tsx": $dashboard_clouds_azure_index,
    "./routes/dashboard/clouds/azure/new.tsx": $dashboard_clouds_azure_new,
    "./routes/dashboard/clouds/calz.tsx": $dashboard_clouds_calz,
    "./routes/dashboard/enterprise/index.tsx": $dashboard_enterprise_index,
    "./routes/dashboard/github-app/index.tsx": $dashboard_github_app_index,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/jwt/index.tsx": $dashboard_jwt_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EntepriseManagementItem.tsx": $EntepriseManagementItem,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
