name: Build, Push and Deploy

on: 
  push:
    branches: main

env:
  MainBranch: main
  MainFormat: "${major}.${minor}.${patch}"
  IMAGE_NAME: everything-as-code:latest
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set variables
        id: vars
        run: |
          echo "currentBranch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Set main version format
        id: mainFormat
        if: steps.vars.outputs.currentBranch == env.MainBranch
        run: echo 'format=${{ env.MainFormat }}' >> $GITHUB_OUTPUT\

      - name: Set prerelease version format
        id: prereleaseFormat
        if: steps.vars.outputs.currentBranch != env.MainBranch
        run: echo 'format=${{ env.MainFormat }}-${{ steps.vars.outputs.currentBranch }}' >> $GITHUB_OUTPUT\

      - name: Deno Setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.4

      - name: Deno Cache
        run: deno cache --reload main.ts

      - name: Set Version ${{ steps.mainFormat.outputs.format || steps.prereleaseFormat.outputs.format }}
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: ${{ steps.mainFormat.outputs.format || steps.prereleaseFormat.outputs.format }}
          # namespace: ${{ steps.vars.outputs.currentBranch == env.MainBranch && null || steps.vars.outputs.currentBranch }}
          # search_commit_body: false
          bump_each_commit: true
          user_format_type: "json"
          enable_prerelease_mode: ${{ steps.vars.outputs.currentBranch != env.MainBranch }}

      # - name: NPM Package Build
      #   run: |
      #     deno task npm:build ${{ steps.version.outputs.version }}
      #     npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      # - name: NPM Package Publish Release
      #   if: steps.vars.outputs.currentBranch == env.MainBranch
      #   run: deno task npm:publish

      # - name: NPM Package Publish Prerelease
      #   if: steps.vars.outputs.currentBranch != env.MainBranch
      #   run: deno task npm:publish --tag ${{ steps.vars.outputs.currentBranch }}

      - name: Tag commit ${{ steps.version.outputs.version }}
        run: |
          git tag v${{ steps.version.outputs.version }} ${{ steps.commit.outputs.commit }}
          git push origin v${{ steps.version.outputs.version }}
            
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # - name: 'Create env file'
      #   run: |
      #     touch .env
      #     echo ${{ secrets.ENV_FILE }} >> .env
      #     cat .env
      
      - name: Deno Setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.2

      # - name: Deno Build
      #   run: deno task build

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}
          context: .
          file: Dockerfile
          load: false     
